In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Admin\Downloads\Applications.csv")

In [3]:
df.head()

,application,program,batch,name,email,phone,current_status,completed_step,submission_date,general_manager,...,statement_of_purpose,payment_status,amount,notes,owner_email,lead_stage,test,token,candidate_id,lead_number
0,IITJMETBT1092410156,IIT Jodhpur - School of Management and Entrepr...,1,Neelam Venkata Akash,neelamvenkataakash@gmail.com,8770175185,No Status,Step 3,03-09-2024 18:09,Akshit Mittal,...,My journey toward pursuing a career in Technol...,Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IITJMETBT1092410288,IIT Jodhpur - School of Management and Entrepr...,1,ChiragDakshikar,chiragdakshikar@gmail.com,8657195171,Reject,Step 3,05-09-2024 19:06,Akshit Mittal,...,My journey in the technology field began with ...,Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IITJMETBT1122429396,IIT Jodhpur - School of Management and Entrepr...,1,ValmikJaware,valmikjaware@gmail.com,9116197117,No Status,Step 3,27-12-2024 02:40,Akshit Mittal,...,"I am a lawyer, with graduation & Post graduati...",Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IITJMETBT108249920,IIT Jodhpur - School of Management and Entrepr...,1,VaibhavMishra,mishravaibhav2233@gmail.com,6106811506,No Status,Step 3,30-08-2024 15:03,Akshit Mittal,...,Statement of Purpose \r\nI am writing to apply...,Payment Not Received,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,IITJMETBT108249881,IIT Jodhpur - School of Management and Entrepr...,1,KanishkaUtsav,kanishkautsav@gmail.com,8574006311,Approved,Step 3,29-08-2024 19:51,Akshit Mittal,...,"I am Kanishka Utsav, an accomplished IT Projec...",Payment Not Received,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 56 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   application                   216 non-null    object
 1   program                       216 non-null    object
 2   batch                         216 non-null    int64
 3   name                          216 non-null    object
 4   email                         194 non-null    object
 5   phone                         216 non-null    int64
 6   current_status                216 non-null    object
 7   completed_step                216 non-null    object
 8   submission_date               216 non-null    object
 9   general_manager               216 non-null    object
 10  source                        216 non-null    object
 11  date_of_birth                 216 non-null    object
 12  current_country               216 non-null    object
 13  current_state                 216 non-null    object
 14  current_city                  216 non-null    object
 15  current_pincode               216 non-null    object
 16  permanent_country             216 non-null    object
 17  permanent_state               216 non-null    object
 18  permanent_city                216 non-null    object
 19  permanent_pincode             212 non-null    float64
 20  identity_proof                216 non-null    object
 21  x_school_name                 216 non-null    object
 22  x_passing_year                216 non-null    int64
 23  x_percentage                  216 non-null    object
 24  xii_school_name               216 non-null    object
 25  xii_board                     214 non-null    object
 26  xii_specialization            216 non-null    object
 27  xii_year                      216 non-null    int64
 28  xii_percentage                216 non-null    object
 29  bachelor_degree               216 non-null    object
 30  bachelor_other_degree         12 non-null     object
 31  branch_bachelor               206 non-null    object
 32  bachelor_percentage           216 non-null    object
 33  bachelor_passing_year         216 non-null    int64
 34  bachelor_university           216 non-null    object
 35  post_graduation               51 non-null     object
 36  master_other                  9 non-null      object
 37  post_graduation_percentage    46 non-null     float64
 38  post_graduation_branch        48 non-null     object
 39  post_graduation_passing_year  50 non-null     float64
 40  post_graduation_university    49 non-null     object
 41  year_of_experience            216 non-null    int64
 42  current_company               205 non-null    object
 43  industry                      204 non-null    object
 44  designation                   203 non-null    object
 45  joining_date                  206 non-null    object
 46  statement_of_purpose          215 non-null    object
 47  payment_status                216 non-null    object
 48  amount                        0 non-null      float64
 49  notes                         0 non-null      float64
 50  owner_email                   210 non-null    object
 51  lead_stage                    210 non-null    object
 52  test                          148 non-null    float64
 53  token                         74 non-null     float64
 54  candidate_id                  0 non-null      float64
 55  lead_number                   0 non-null      float64
dtypes: float64(9), int64(6), object(41)
memory usage: 94.6+ KB

In [6]:
df.describe()

,batch,phone,permanent_pincode,x_passing_year,xii_year,bachelor_passing_year,post_graduation_percentage,post_graduation_passing_year,year_of_experience,amount,notes,test,token,candidate_id,lead_number
count,216.0,2.160000e+02,212.000000,216.000000,216.000000,216.000000,46.000000,50.000000,216.000000,0.0,0.0,148.0,74.0,0.0,0.0
mean,1.0,8.544791e+09,448738.495283,2008.342593,2010.726852,2015.069444,58.230435,2016.340000,11.490741,NaN,NaN,1.0,1.0,NaN,NaN
std,0.0,1.097880e+09,223175.359781,6.402996,6.534660,6.165907,29.179885,6.345849,19.810965,NaN,NaN,0.0,0.0,NaN,NaN
min,1.0,6.101511e+09,110001.000000,1985.000000,1988.000000,1991.000000,3.070000,1996.000000,1.000000,NaN,NaN,1.0,1.0,NaN,NaN
25%,1.0,7.875303e+09,249544.250000,2004.000000,2007.000000,2011.000000,56.127500,2013.000000,4.000000,NaN,NaN,1.0,1.0,NaN,NaN
50%,1.0,8.753009e+09,452008.500000,2009.000000,2012.000000,2016.000000,66.125000,2017.000000,8.000000,NaN,NaN,1.0,1.0,NaN,NaN
75%,1.0,9.562882e+09,625293.250000,2012.000000,2015.250000,2020.000000,76.502500,2022.000000,11.000000,NaN,NaN,1.0,1.0,NaN,NaN
max,1.0,9.999811e+09,854202.000000,2020.000000,2023.000000,2024.000000,100.000000,2024.000000,100.000000,NaN,NaN,1.0,1.0,NaN,NaN

In [7]:
df.drop_duplicates()

,application,program,batch,name,email,phone,current_status,completed_step,submission_date,general_manager,...,statement_of_purpose,payment_status,amount,notes,owner_email,lead_stage,test,token,candidate_id,lead_number
0,IITJMETBT1092410156,IIT Jodhpur - School of Management and Entrepr...,1,Neelam Venkata Akash,neelamvenkataakash@gmail.com,8770175185,No Status,Step 3,03-09-2024 18:09,Akshit Mittal,...,My journey toward pursuing a career in Technol...,Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IITJMETBT1092410288,IIT Jodhpur - School of Management and Entrepr...,1,ChiragDakshikar,chiragdakshikar@gmail.com,8657195171,Reject,Step 3,05-09-2024 19:06,Akshit Mittal,...,My journey in the technology field began with ...,Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IITJMETBT1122429396,IIT Jodhpur - School of Management and Entrepr...,1,ValmikJaware,valmikjaware@gmail.com,9116197117,No Status,Step 3,27-12-2024 02:40,Akshit Mittal,...,"I am a lawyer, with graduation & Post graduati...",Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IITJMETBT108249920,IIT Jodhpur - School of Management and Entrepr...,1,VaibhavMishra,mishravaibhav2233@gmail.com,6106811506,No Status,Step 3,30-08-2024 15:03,Akshit Mittal,...,Statement of Purpose \r\nI am writing to apply...,Payment Not Received,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,IITJMETBT108249881,IIT Jodhpur - School of Management and Entrepr...,1,KanishkaUtsav,kanishkautsav@gmail.com,8574006311,Approved,Step 3,29-08-2024 19:51,Akshit Mittal,...,"I am Kanishka Utsav, an accomplished IT Projec...",Payment Not Received,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,IITJMETBT1092412358,IIT Jodhpur - School of Management and Entrepr...,1,SaurabhRelia,saurabhrelia@gmail.com,9810519615,Approved,Step 3,24-09-2024 20:59,Akshit Mittal,...,I had been working as an IT Professional for o...,Payment Not Received,NaN,NaN,Simran.rana@futurense.com,Not Interested,NaN,NaN,NaN,NaN
212,IITJMETBT1092412692,IIT Jodhpur - School of Management and Entrepr...,1,AshiqurRahman,ashiqurrahman@gmail.com,8472071440,No Status,Step 3,26-09-2024 23:20,Akshit Mittal,...,"Hi, I am Ashiqur Rahman, holding a Master’s de...",Payment Not Received,NaN,NaN,akshit.mittal@futurense.com,Not Interested,1.0,NaN,NaN,NaN
213,IITJMETBT1102416080,IIT Jodhpur - School of Management and Entrepr...,1,RajibSamanta,rajibsamanta@gmail.com,8370982356,Approved,Step 3,24-10-2024 15:48,Akshit Mittal,...,I would like to enroll for a management course...,Payment Not Received,NaN,NaN,akshit.mittal@futurense.com,Not Interested,1.0,NaN,NaN,NaN
214,IITJMETBT1122424279,IIT Jodhpur - School of Management and Entrepr...,1,Debangshi Addya,debangshiaddya@gmail.com,6189699118,Reject,Step 3,03-12-2024 11:28,Akshit Mittal,...,AI Tools and there uses are very much required...,Payment Not Received,NaN,NaN,rupanshi.s@futurense.com,Not Eligible,NaN,NaN,NaN,NaN
215,IITJMETBT1102415532,IIT Jodhpur - School of Management and Entrepr...,1,ShankarAnand,getshankaranand@gmail.com,9585117771,Approved,Step 3,18-10-2024 13:22,Akshit Mittal,...,As a Technical Lead in Network Security with o...,Payment Not Received,NaN,NaN,vinti@futurense.com,Not Interested,1.0,NaN,NaN,NaN

In [10]:
df['branch_bachelor'].fillna("Unknown", inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21804\320869080.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['branch_bachelor'].fillna("Unknown", inplace=True)

In [11]:
df['joining_date'].fillna(pd.to_datetime("2000-01-01"), inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21804\2630390892.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['joining_date'].fillna(pd.to_datetime("2000-01-01"), inplace=True)

In [12]:
df['branch_bachelor'].fillna("Unknown", inplace=True)

In [13]:
df['joining_date'].fillna(pd.to_datetime("2000-01-01"), inplace=True)

In [14]:
df.dropna(subset=['date_of_birth'])

,application,program,batch,name,email,phone,current_status,completed_step,submission_date,general_manager,...,statement_of_purpose,payment_status,amount,notes,owner_email,lead_stage,test,token,candidate_id,lead_number
0,IITJMETBT1092410156,IIT Jodhpur - School of Management and Entrepr...,1,Neelam Venkata Akash,neelamvenkataakash@gmail.com,8770175185,No Status,Step 3,03-09-2024 18:09,Akshit Mittal,...,My journey toward pursuing a career in Technol...,Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IITJMETBT1092410288,IIT Jodhpur - School of Management and Entrepr...,1,ChiragDakshikar,chiragdakshikar@gmail.com,8657195171,Reject,Step 3,05-09-2024 19:06,Akshit Mittal,...,My journey in the technology field began with ...,Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IITJMETBT1122429396,IIT Jodhpur - School of Management and Entrepr...,1,ValmikJaware,valmikjaware@gmail.com,9116197117,No Status,Step 3,27-12-2024 02:40,Akshit Mittal,...,"I am a lawyer, with graduation & Post graduati...",Payment Not Received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IITJMETBT108249920,IIT Jodhpur - School of Management and Entrepr...,1,VaibhavMishra,mishravaibhav2233@gmail.com,6106811506,No Status,Step 3,30-08-2024 15:03,Akshit Mittal,...,Statement of Purpose \r\nI am writing to apply...,Payment Not Received,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,IITJMETBT108249881,IIT Jodhpur - School of Management and Entrepr...,1,KanishkaUtsav,kanishkautsav@gmail.com,8574006311,Approved,Step 3,29-08-2024 19:51,Akshit Mittal,...,"I am Kanishka Utsav, an accomplished IT Projec...",Payment Not Received,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,IITJMETBT1092412358,IIT Jodhpur - School of Management and Entrepr...,1,SaurabhRelia,saurabhrelia@gmail.com,9810519615,Approved,Step 3,24-09-2024 20:59,Akshit Mittal,...,I had been working as an IT Professional for o...,Payment Not Received,NaN,NaN,Simran.rana@futurense.com,Not Interested,NaN,NaN,NaN,NaN
212,IITJMETBT1092412692,IIT Jodhpur - School of Management and Entrepr...,1,AshiqurRahman,ashiqurrahman@gmail.com,8472071440,No Status,Step 3,26-09-2024 23:20,Akshit Mittal,...,"Hi, I am Ashiqur Rahman, holding a Master’s de...",Payment Not Received,NaN,NaN,akshit.mittal@futurense.com,Not Interested,1.0,NaN,NaN,NaN
213,IITJMETBT1102416080,IIT Jodhpur - School of Management and Entrepr...,1,RajibSamanta,rajibsamanta@gmail.com,8370982356,Approved,Step 3,24-10-2024 15:48,Akshit Mittal,...,I would like to enroll for a management course...,Payment Not Received,NaN,NaN,akshit.mittal@futurense.com,Not Interested,1.0,NaN,NaN,NaN
214,IITJMETBT1122424279,IIT Jodhpur - School of Management and Entrepr...,1,Debangshi Addya,debangshiaddya@gmail.com,6189699118,Reject,Step 3,03-12-2024 11:28,Akshit Mittal,...,AI Tools and there uses are very much required...,Payment Not Received,NaN,NaN,rupanshi.s@futurense.com,Not Eligible,NaN,NaN,NaN,NaN
215,IITJMETBT1102415532,IIT Jodhpur - School of Management and Entrepr...,1,ShankarAnand,getshankaranand@gmail.com,9585117771,Approved,Step 3,18-10-2024 13:22,Akshit Mittal,...,As a Technical Lead in Network Security with o...,Payment Not Received,NaN,NaN,vinti@futurense.com,Not Interested,1.0,NaN,NaN,NaN

In [17]:
df['x_percentage'] = df['x_percentage'].astype(str).str.replace('%', '').str.strip()
df['x_percentage'] = pd.to_numeric(df['x_percentage'], errors='coerce')

df['bachelor_percentage'] = df['bachelor_percentage'].astype(str).str.replace('%', '').str.strip()
df['bachelor_percentage'] = pd.to_numeric(df['bachelor_percentage'], errors='coerce')

In [18]:
df['x_percentage'].fillna(df['x_percentage'].median(), inplace=True)
df['bachelor_percentage'].fillna(df['bachelor_percentage'].median(), inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21804\1032193259.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['x_percentage'].fillna(df['x_percentage'].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_21804\1032193259.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bachelor_percentage'].fillna(df['bachelor_percentage'].median(), inplace=True)

In [19]:
percentage_columns = ['x_percentage', 'xii_percentage', 'bachelor_percentage']

for col in percentage_columns:
    df[col] = df[col].astype(str).str.replace('%', '').str.strip()

    df[col] = pd.to_numeric(df[col], errors='coerce')

    df[col].fillna(df[col].median(), inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_21804\987602760.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_21804\987602760.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_21804\987602760.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
print(df[percentage_columns].dtypes)          
print(df[percentage_columns].isnull().sum())

x_percentage           float64
xii_percentage         float64
bachelor_percentage    float64
dtype: object
x_percentage           0
xii_percentage         0
bachelor_percentage    0
dtype: int64